### ISSUE TITLE
Error when installing the classAccuracy plugin from zip

### ISSUE THREAD

**Issue by oytisa** [remotesensinginfo/classaccuracy#2]
During the installation from zip file, an error occurred in QGIS 3.10.10
here below is the error report. I guess if the hyphen is a problem or Plugin name mismatch: the plugin main folder name in the compressed file and the original plugin package name.
![xxxx](https://user-images.githubusercontent.com/25427373/94731206-11ce8d80-036d-11eb-9087-4038b7628bad.JPG)

**Comment by breylla** [comment]
I got the same error!

**Comment by Nevarro** [comment]
Got the same error as well. 

Edit: Unzip the file and re-zip the folder "ClassAccuracyMain" without the README.md-file. Then add the newly created zip-file as a QGIS plugin (got the tip from NASA ARSET).

**Comment by breylla** [comment]
Thank you @Phoara It worked :)

**Comment by klh5** [comment]
In case it helps anyone, I also had to remove "QVersionNumber" from the list of imports in rsgisclassacc.py.

**Comment by oytisa** [comment]
> Thank you Phoara for saving my time. It worked!
